source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'puma', '~> 6.0'
gem 'faraday', '~> 2.0'
gem 'json'
gem 'dotenv', '~> 2.8'
gem 'rack-cors', '~> 2.0'
gem 'rack-protection', '~> 3.0'
gem 'rack-attack', '~> 6.0'
gem 'jwt', '~> 2.7'
